### ISSUE TITLE
Hey can you make commands how to run the server, cause I have several Problems when I try to run it.

### ISSUE THREAD

**Issue by berknator** [Ronik22/Django_Social_Network_App#1]
I made a virtual env. and load the requirements. After that i tried: python manage.py runserver

It showed me this:

(myenv) C:\Users\Win10\Desktop\network-app>python manage.py runserver
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Win10\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Win10\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Win10\Desktop\network-app\myenv\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Win10\Desktop\network-app\myenv\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Win10\Desktop\network-app\myenv\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "C:\Users\Win10\Desktop\network-app\myenv\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\Win10\Desktop\network-app\myenv\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Win10\Desktop\network-app\myenv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Win10\Desktop\network-app\myenv\lib\site-packages\django\apps\registry.py", line 122, in populate
    app_config.ready()
  File "C:\Users\Win10\Desktop\network-app\myenv\lib\site-packages\django\contrib\admin\apps.py", line 27, in ready
    self.module.autodiscover()
  File "C:\Users\Win10\Desktop\network-app\myenv\lib\site-packages\django\contrib\admin\__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "C:\Users\Win10\Desktop\network-app\myenv\lib\site-packages\django\utils\module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "C:\Users\Win10\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Win10\Desktop\network-app\myenv\lib\site-packages\django\contrib\auth\admin.py", line 6, in <module>
    from django.contrib.auth.forms import (
  File "C:\Users\Win10\Desktop\network-app\myenv\lib\site-packages\django\contrib\auth\forms.py", line 11, in <module>
    from django.contrib.auth.tokens import default_token_generator
  File "C:\Users\Win10\Desktop\network-app\myenv\lib\site-packages\django\contrib\auth\tokens.py", line 117, in <module>
    default_token_generator = PasswordResetTokenGenerator()
  File "C:\Users\Win10\Desktop\network-app\myenv\lib\site-packages\django\contrib\auth\tokens.py", line 18, in __init__
    self.secret = self.secret or settings.SECRET_KEY
  File "C:\Users\Win10\Desktop\network-app\myenv\lib\site-packages\django\conf\__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by Ronik22** [comment]
The error comes from missing **SECRET_KEY**. In "/myproject/settings.py /" dotenv is loading a **".env"** file to get SECRET_KEY but there is no such file in the root directory. Instead, there is a **".test.env"** file. I have not pushed the actual ".env" since it had my creds. You can **rename** the **".test.env"** to **".env"** and run make migrations, migrate, create a superuser, and then runserver. Also fill in **other details** in the env file to use the app fully. Hope this solves your problem. Thank You!!
